<?php

namespace Database\Seeders;

use App\Models\Car;
use App\Models\City;
use App\Models\User;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hosts = User::where('role', 'host')->get()->keyBy('email');
        $cities = City::all()->keyBy('slug');

        foreach ([
            [
                'city_slug' => 'bangkok',
                'host_email' => 'narin.host@driveflow.test',
                'slug' => 'tesla-model-y-midnight',
                'name' => 'Tesla Model Y Midnight',
                'brand' => 'Tesla',
                'model' => 'Model Y',
                'year' => 2024,
                'car_type' => 'Electric SUV',
                'transmission' => 'Automatic',
                'seats' => 5,
                'fuel_type' => 'Electric',
                'location_name' => 'Sukhumvit BTS pickup zone',
                'price_per_day' => 119,
                'rating' => 5.0,
                'trips_count' => 82,
                'short_description' => 'A premium electric SUV for city meetings and weekend escapes.',
                'description' => 'Fast charging, whisper-quiet cabin, panoramic roof, and delivery options that match a Turo-style premium experience.',
                'image_url' => 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1600&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80',
                ],
                'features' => ['Autopilot', 'Premium audio', 'Glass roof', 'Fast charging', 'Airport pickup'],
                'pickup_options' => ['self_pickup', 'airport_meetup', 'doorstep_delivery'],
                'delivery_fee' => 18,
                'is_featured' => true,
                'instant_book' => true,
            ],
            [
                'city_slug' => 'bangkok',
                'host_email' => 'mali.host@driveflow.test',
                'slug' => 'bmw-330e-riverline',
                'name' => 'BMW 330e Riverline',
                'brand' => 'BMW',
                'model' => '330e',
                'year' => 2023,
                'car_type' => 'Luxury Sedan',
                'transmission' => 'Automatic',
                'seats' => 5,
                'fuel_type' => 'Hybrid',
                'location_name' => 'Rama 9 business district',
                'price_per_day' => 102,
                'rating' => 4.9,
                'trips_count' => 51,
                'short_description' => 'Refined plug-in hybrid comfort for polished city travel.',
                'description' => 'Designed for executives who want quiet luxury, leather seats, and low city fuel consumption.',
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1600&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1600&q=80',
                ],
                'features' => ['Leather interior', 'Hybrid efficiency', 'Wireless Apple CarPlay', 'Adaptive cruise'],
                'pickup_options' => ['self_pickup', 'doorstep_delivery'],
                'delivery_fee' => 12,
                'is_featured' => true,
                'instant_book' => true,
            ],
            [
                'city_slug' => 'chiang-mai',
                'host_email' => 'preecha.host@driveflow.test',
                'slug' => 'toyota-fortuner-altitude',
                'name' => 'Toyota Fortuner Altitude',
                'brand' => 'Toyota',
                'model' => 'Fortuner',
                'year' => 2024,
                'car_type' => 'SUV',
                'transmission' => 'Automatic',
                'seats' => 7,
                'fuel_type' => 'Diesel',
                'location_name' => 'Chiang Mai airport arrivals',
                'price_per_day' => 94,
                'rating' => 4.8,
                'trips_count' => 43,
                'short_description' => 'Large-group comfort with strong mountain-road confidence.',
                'description' => 'Perfect for family trips, temple runs, and luggage-heavy airport transfers with room for everyone.',
                'image_url' => 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1600&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1600&q=80',
                ],
                'features' => ['7 seats', 'Large trunk', 'Reverse camera', 'Airport meetup', 'Roadside support'],
                'pickup_options' => ['self_pickup', 'airport_meetup'],
                'delivery_fee' => 15,
                'is_featured' => true,
                'instant_book' => false,
            ],
            [
                'city_slug' => 'chiang-mai',
                'host_email' => 'narin.host@driveflow.test',
                'slug' => 'mini-cooper-sunrise',
                'name' => 'Mini Cooper Sunrise',
                'brand' => 'Mini',
                'model' => 'Cooper',
                'year' => 2022,
                'car_type' => 'Compact',
                'transmission' => 'Automatic',
                'seats' => 4,
                'fuel_type' => 'Petrol',
                'location_name' => 'Nimmanhaemin one-nimman hub',
                'price_per_day' => 77,
                'rating' => 4.7,
                'trips_count' => 37,
                'short_description' => 'Playful city handling for cafe hopping and old-town cruising.',
                'description' => 'A compact favorite for couples who want style, responsive steering, and easy parking.',
                'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1600&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1600&q=80',
                ],
                'features' => ['Compact parking', 'Sport mode', 'Wireless charger', 'Downtown pickup'],
                'pickup_options' => ['self_pickup'],
                'delivery_fee' => 0,
                'is_featured' => false,
                'instant_book' => true,
            ],
            [
                'city_slug' => 'phuket',
                'host_email' => 'mali.host@driveflow.test',
                'slug' => 'ford-mustang-ocean-drive',
                'name' => 'Ford Mustang Ocean Drive',
                'brand' => 'Ford',
                'model' => 'Mustang Convertible',
                'year' => 2023,
                'car_type' => 'Convertible',
                'transmission' => 'Automatic',
                'seats' => 4,
                'fuel_type' => 'Petrol',
                'location_name' => 'Patong beachfront collection point',
                'price_per_day' => 138,
                'rating' => 4.9,
                'trips_count' => 29,
                'short_description' => 'Sunset drives and island weekends with a dramatic top-down profile.',
                'description' => 'A head-turning convertible for scenic coastline routes, resort arrivals, and beach-club nights.',
                'image_url' => 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1600&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80',
                ],
                'features' => ['Convertible roof', 'Premium sound', 'Resort delivery', 'Photo-ready finish'],
                'pickup_options' => ['airport_meetup', 'doorstep_delivery'],
                'delivery_fee' => 24,
                'is_featured' => true,
                'instant_book' => false,
            ],
            [
                'city_slug' => 'phuket',
                'host_email' => 'preecha.host@driveflow.test',
                'slug' => 'byd-seal-coastline',
                'name' => 'BYD Seal Coastline',
                'brand' => 'BYD',
                'model' => 'Seal',
                'year' => 2024,
                'car_type' => 'Electric Sedan',
                'transmission' => 'Automatic',
                'seats' => 5,
                'fuel_type' => 'Electric',
                'location_name' => 'Phuket Town pickup lounge',
                'price_per_day' => 88,
                'rating' => 4.8,
                'trips_count' => 18,
                'short_description' => 'Smooth electric range for the island with premium cabin tech.',
                'description' => 'Ideal for travelers wanting quiet acceleration, modern screens, and a more affordable EV experience.',
                'image_url' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1600&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1600&q=80',
                ],
                'features' => ['Panoramic roof', 'Fast charging', 'Ventilated seats', 'Airport pickup'],
                'pickup_options' => ['self_pickup', 'airport_meetup'],
                'delivery_fee' => 16,
                'is_featured' => false,
                'instant_book' => true,
            ],
            [
                'city_slug' => 'pattaya',
                'host_email' => 'narin.host@driveflow.test',
                'slug' => 'mercedes-gla-nightshift',
                'name' => 'Mercedes GLA Nightshift',
                'brand' => 'Mercedes-Benz',
                'model' => 'GLA',
                'year' => 2023,
                'car_type' => 'Luxury SUV',
                'transmission' => 'Automatic',
                'seats' => 5,
                'fuel_type' => 'Petrol',
                'location_name' => 'Central Pattaya pickup deck',
                'price_per_day' => 111,
                'rating' => 4.9,
                'trips_count' => 34,
                'short_description' => 'Premium crossover comfort for business trips and nightlife escapes.',
                'description' => 'This compact luxury SUV balances style and easy maneuvering for city traffic and coast roads.',
                'image_url' => 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1600&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1600&q=80',
                    'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1600&q=80',
                ],
                'features' => ['Ambient lighting', 'Premium sound', 'Doorstep delivery', 'Blind spot assist'],
                'pickup_options' => ['self_pickup', 'doorstep_delivery'],
                'delivery_fee' => 19,
                'is_featured' => true,
                'instant_book' => true,
            ],
        ] as $car) {
            Car::updateOrCreate(
                ['slug' => $car['slug']],
                [
                    'city_id' => $cities[$car['city_slug']]->id,
                    'host_id' => $hosts[$car['host_email']]->id,
                    'slug' => $car['slug'],
                    'name' => $car['name'],
                    'brand' => $car['brand'],
                    'model' => $car['model'],
                    'year' => $car['year'],
                    'car_type' => $car['car_type'],
                    'transmission' => $car['transmission'],
                    'seats' => $car['seats'],
                    'fuel_type' => $car['fuel_type'],
                    'location_name' => $car['location_name'],
                    'price_per_day' => $car['price_per_day'],
                    'rating' => $car['rating'],
                    'trips_count' => $car['trips_count'],
                    'short_description' => $car['short_description'],
                    'description' => $car['description'],
                    'image_url' => $car['image_url'],
                    'gallery' => $car['gallery'],
                    'features' => $car['features'],
                    'pickup_options' => $car['pickup_options'],
                    'delivery_fee' => $car['delivery_fee'],
                    'is_featured' => $car['is_featured'],
                    'is_active' => true,
                    'instant_book' => $car['instant_book'],
                ],
            );
        }
    }
}
